### ISSUE TITLE
Rmath isn't building on Travis

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/Rmath-julia#17]
This seems to be taking out downstream Travis builds, which are getting back a server error (HTTP status code 500) when attempting to download https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz.

ref https://github.com/jeff-regier/Celeste.jl/pull/590 and https://github.com/jeff-regier/Celeste.jl/pull/594#issuecomment-285397286

**Comment by simonbyrne** [comment]
That's bizarre. I'll contact GitHub.

**Comment by tkelman** [comment]
Is it still happening? That link works okay for me.

**Comment by jrevels** [comment]
Yup, I just restarted a build [here](https://travis-ci.org/jeff-regier/Celeste.jl/builds/209390054) and it happened again.

> That link works okay for me.

Maybe it depends on where you're getting served? I'm still getting a `500: Internal Server Error` when I try the link locally.

**Comment by ararslan** [comment]
Doesn't seem to be working for me locally either.

**Comment by montyvesselinov** [comment]
it fails for me as well.

https://travis-ci.org/madsjulia/ReusableFunctions.jl/jobs/209445198

**Comment by simonbyrne** [comment]
I just received an email from GitHub: they said the issue should now be fixed. Please reopen if it occurs again.
