### ISSUE TITLE
Rmath won't build

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/Rmath-julia#23]
```
julia> using Rmath
ERROR: LoadError: Rmath not properly installed. Please run Pkg.build("Rmath") and restart julia
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:569
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/peterdeffebach/.julia/v0.6/Rmath/src/Rmath.jl, in expression starting on line 15
ERROR: Failed to precompile Rmath to /Users/peterdeffebach/.julia/lib/v0.6/Rmath.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398
```

Running ```Pkg.build("Rmath")``` does not succeed either. I am using OSX High Sierra 10.13.

**Comment by simonbyrne** [comment]
Care to expand?

**Comment by pdeffebach** [comment]
Update: installing Command Line tools for terminal fixes the issue. All I needed to do was do ```xcode-select --install``` in the terminal. 
Is this expected behavior? To what extent should users know to anticipate this?

**Comment by ararslan** [comment]
I think in general it's expected that to build things from source on macOS, users need the Xcode command line tools installs; that isn't specific to Rmath.

**Comment by lawanfalalu** [comment]
I am getting the same ERROR I am using Ubuntu 14
ERROR: LoadError: Rmath not properly installed. Please run Pkg.build("Rmath") and restart julia
 in error(::String) at ./error.jl:21
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /home/spg/.julia/v0.5/Rmath/src/Rmath.jl, in expression starting on line 17
ERROR: LoadError: LoadError: Failed to precompile Rmath to /home/spg/.julia/lib/v0.5/Rmath.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /home/spg/.julia/v0.5/StatsFuns/src/rmath.jl, in expression starting on line 6
while loading /home/spg/.julia/v0.5/StatsFuns/src/StatsFuns.jl, in expression starting on line 228
ERROR: LoadError: Failed to precompile StatsFuns to /home/spg/.julia/lib/v0.5/StatsFuns.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /home/spg/.julia/v0.5/Distributions/src/Distributions.jl, in expression starting on line 6
ERROR: LoadError: LoadError: Failed to precompile Distributions to /home/spg/.julia/lib/v0.5/Distributions.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /home/spg/.julia/v0.5/TensorFlow/src/variable.jl, in expression starting on line 30
while loading /home/spg/.julia/v0.5/TensorFlow/src/TensorFlow.jl, in expression starting on line 187
ERROR: Failed to precompile TensorFlow to /home/spg/.julia/lib/v0.5/TensorFlow.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422

**Comment by simonbyrne** [comment]
Not sure about that one: maybe try deleting `/home/spg/.julia/v0.5/Rmath/deps/downloads/v0.2.0.tar.gz` and rerun `Pkg.build("Rmath")`?

**Comment by lawanfalalu** [comment]
Issue solved after re-running Pkg.update() a while after a bug was fixed
based on a new issue I raised
